### ISSUE TITLE
Нельзя передавать свое значение в пропсы Theme

### ISSUE THREAD

**Issue by tsvetta** [Nitive/whitepaper-react#4]
![image](https://user-images.githubusercontent.com/4266798/51478487-a7460b80-1d9c-11e9-8465-b698c9131778.png)

**Comment by Nitive** [comment]
Это правильно — если передать другое значение, то просто не добавится никакого css.
Если хочется использовать другой шрифт, не нужно использовать этот пропс, вместо этого нужно сделать другой компонент, который будет определять переменные `--font-sans`, `--font-serif` и `--font-mono`
